### ISSUE TITLE
Pagespeed unable to see Nginx GZip

### ISSUE THREAD

**Issue by Mr-Anonymous** [pagespeed/ngx_pagespeed#844]
I keep getting this warning from Pagespeed in my /var/log/nginx/error.log 
```
[warn] 2471#0: pagespeed: cannot set gzip, command not found in /etc/nginx/nginx.conf:12
[info] 12823#0: pagespeed: rollback gzip, explicit configuration in /etc/nginx/nginx.conf:83
```

I have enabled gzip in nginx.conf like this:

```
        gzip on;
        gzip_disable "MSIE [1-6]\.";

        gzip_vary on;
        gzip_min_length 10240;
        gzip_proxied any;
        gzip_comp_level 5;
        gzip_buffers 16 8k;
        gzip_http_version 1.1;
        gzip_types text/plain text/css application/json application/x-javascript application/javascript text/xml application/xml application/xml+rss text/javascript;
```

When I check my site using the gzip testing tool it shows its gzip enabled but pagespeed is showing error in the log. I then added this to my pagespeed.conf as per the guide [here](https://developers.google.com/speed/pagespeed/module/system): 
```
pagespeed FetchWithGzip on;
```

It was then showing this error:
```
[emerg] 12820#0: "pagespeed" directive "FetchWithGzip" cannot be set at this scope. in /etc/nginx/pagespeed.conf:44
```

I then read [this ticket] (https://github.com/pagespeed/ngx_pagespeed/issues/378) and I changed the line to this: 
```
pagespeed CustomFetchHeader Accept-Encoding gzip;
```

It didnt do anything and was still showing the "pagespeed: cannot set gzip" error. Why is pagespeed unable to see the gzip command in Nginx config file?

**Comment by jenssegers** [comment]
I keep getting `pagespeed: rollback gzip, explicit configuration` as well. Is this fixed in dotdeb already?

**Comment by oschaaf** [comment]
@jenssegers I don't think so, but it should be fixed with the next release. Meantime, the message itself can be ignored as it is not indicative of problems.

**Comment by jenssegers** [comment]
Rewrite images is not working for me, is it not related to this error message?

**Comment by oschaaf** [comment]
@jenssegers I can't relate that message to rewrite_images not working, so I would be surprised. Could you post (or pm) a link to your website so I can have a look?

**Comment by jenssegers** [comment]
I've sent you an email, thanks in advance!

**Comment by oschaaf** [comment]
In case others read this: @jenssegers problem with rewrite_images turned out to be unrelated to this issue and has been resolved via email.

**Comment by tekert** [comment]
Uhm, I'm surprised this problem is not fixed yet
Debian 8.5, nginx-extra | 1.10.1-1~dotdeb+8.2
x-page-speed: 1.11.33.2-0

Exact same problem, similar config:
service nginx reload
[warn] pagespeed: cannot set gzip, command not found in /etc/nginx/nginx.conf:14

service nginx restart
[info] pagespeed: rollback gzip, explicit configuration in /etc/nginx/nginx.conf:67

**Comment by huibaolin** [comment]
PageSpeed 1.11.33.3 was just released. It includes several fixes for gzip (Release Notes: https://developers.google.com/speed/pagespeed/module/release_notes). 

Can you give it a try?

**Comment by jeffkaufman** [comment]
Could you paste the `./configure` command you used when building ngx_pagespeed?

**Comment by tekert** [comment]
Its a standard build from dotdeb, saldy i dont have those params.
Can't test right now 1.11.33.3 but i can confirm in dotdeb nginx-extras with pagespeed 1.11.33.2-0 that the duplicated "vary: Accept-Encoding" headers i tought to be related to the gzip error where gone when i set HttpCacheCompressionLevel 0;

**Comment by oschaaf** [comment]
@tekert can you paste the output of `nginx -V`?

**Comment by tekert** [comment]
Sure, here it is:
nginx version: nginx/1.10.1
built with OpenSSL 1.0.1k 8 Jan 2015 (running with OpenSSL 1.0.2h  3 May 2016)
TLS SNI support enabled
configure arguments: --add-module=/usr/src/builddir/debian/modules/naxsi/naxsi_src --with-cc-opt='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-z,relro -Wl,-z,now' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-file-aio --with-threads --with-http_addition_module --with-http_flv_module --with-http_geoip_module=dynamic --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_mp4_module --with-http_perl_module=dynamic --with-http_random_index_module --with-http_secure_link_module --with-http_sub_module --with-http_xslt_module=dynamic --with-mail=dynamic --with-mail_ssl_module --with-stream=dynamic --with-stream_ssl_module --add-module=/usr/src/builddir/debian/modules/headers-more-nginx-module --add-dynamic-module=/usr/src/builddir/debian/modules/nginx-auth-pam --add-module=/usr/src/builddir/debian/modules/nginx-cache-purge --add-module=/usr/src/builddir/debian/modules/nginx-dav-ext-module --add-dynamic-module=/usr/src/builddir/debian/modules/nginx-development-kit --add-module=/usr/src/builddir/debian/modules/nginx-echo --add-module=/usr/src/builddir/debian/modules/ngx-fancyindex --add-module=/usr/src/builddir/debian/modules/nginx-push-stream-module --add-dynamic-module=/usr/src/builddir/debian/modules/nginx-lua --add-module=/usr/src/builddir/debian/modules/nginx-upload-progress --add-module=/usr/src/builddir/debian/modules/nginx-upstream-fair --add-module=/usr/src/builddir/debian/modules/ngx_http_substitutions_filter_module --add-module=/usr/src/builddir/debian/modules/nginx-auth-ldap --add-module=/usr/src/builddir/debian/modules/ngx_http_pinba_module --add-module=/usr/src/builddir/debian/modules/ngx_pagespeed --add-module=/usr/src/builddir/debian/modules/nginx-x-rid-header --add-module=/usr/src/builddir/debian/modules/nginx-rtmp-module --with-ld-opt=-lossp-uuid

**Comment by oschaaf** [comment]
@tekert thanks!


You posted three things, the first is a warning. I hope that the information you just posted will help reproduce it. @keesspoelstra do you have an idea about why this gets logged?
```
service nginx reload
[warn] pagespeed: cannot set gzip, command not found in /etc/nginx/nginx.conf:14
```


The following  is a benign (informational) message, I don't think we need to look into this. ngx_pagespeed is undoing any changes it made for setting up gzip because it sees you have explicit gzip configuration which should override it.
```
service nginx restart
[info] pagespeed: rollback gzip, explicit configuration in /etc/nginx/nginx.conf:67
```


The following is a know issue, and was tracked via https://github.com/pagespeed/ngx_pagespeed/issues/1064. The full fix will be out on the next major release.. 
```
Also im getting duplicated
vary: Accept-Encoding
vary: Accept-Encoding
```

There is  a patch that stopsmultiple vary headers from escaping (but it does not adress the root cause), see https://github.com/pagespeed/ngx_pagespeed/issues/314#issuecomment-232636564

**Comment by Firegarden** [comment]
I am seeing this error and I have 

> pagespeed unplugged 

Which makes me believe that unplugged does not really mean unplugged. 

Error happens when you simply declare a gzip directive in sites configuration

`2018/02/18 03:25:01 [info] 4895#4895: pagespeed: rollback gzip, explicit configuration in /etc/nginx/sites-enabled/`

**Comment by rajuginne** [comment]
i am also getting errors on latest versions both nginx and page speed

**Comment by oschaaf** [comment]
These are not error messages, they are informational messages. 
Having said that, I agree it would be an improvement to not attempt to update gzip configuration for unplugged server{} blocks.
